### PR TITLE
Add ValidateLogin

### PR DESCRIPTION
**Pull request by ethsmith**
I added validatelogin and it works. It validates the user with the given email and password but what it doesn't do is create the session. I assume that is because my code and the WHMCS installation were on two different machines. I haven't tried when the code and WHMCS was on the same machine.

I remember when using the internal API it created the session so again I assume this is because the code and WHMCS were on seperate hosts but maybe WHMCS doesn't set the session when using the external API.

P.S. This is my first code PR in Golang so please let me know if there was better ways to do something or if you have info on the session thing.

### CODE REVIEW

**Comment by ChunkRadius** [comment]
Looks great. Thanks so much!

**Comment by ethsmith** [comment]
np!

**Comment by ethsmith** [comment]
@bradberger I was just curious and was wondering where do you work at where you use this? or is this more of just a personal thing?

**Comment by ChunkRadius** [comment]
Work. More specifically freelance work done for quite a large hosting company.

**Comment by ethsmith** [comment]
Ah cool.

**Pull request merged**
